# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\YDD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        MainWindow.setMinimumSize(QtCore.QSize(800, 650))
        MainWindow.setMaximumSize(QtCore.QSize(800, 650))
        
        icon = QtGui.QIcon()
        
        icon.addPixmap(QtGui.QPixmap("design\\../pics/youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.youtube_icon = QtWidgets.QLabel(self.centralwidget)
        self.youtube_icon.setGeometry(QtCore.QRect(350, 30, 141, 101))
        self.youtube_icon.setMaximumSize(QtCore.QSize(171, 16777215))
        self.youtube_icon.setText("")
        self.youtube_icon.setPixmap(QtGui.QPixmap("design\\../pics/youtube.png"))
        self.youtube_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.youtube_icon.setObjectName("youtube_icon")
        
        self.app_title = QtWidgets.QLabel(self.centralwidget)
        self.app_title.setGeometry(QtCore.QRect(200, 140, 471, 61))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(24)
        
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignCenter)
        self.app_title.setObjectName("app_title")
        
        self.url_label = QtWidgets.QLabel(self.centralwidget)
        self.url_label.setGeometry(QtCore.QRect(100, 240, 131, 61))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(16)
        
        self.url_label.setFont(font)
        self.url_label.setAlignment(QtCore.Qt.AlignCenter)
        self.url_label.setObjectName("url_label")
        
        self.location_label = QtWidgets.QLabel(self.centralwidget)
        self.location_label.setGeometry(QtCore.QRect(100, 360, 121, 61))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(16)
        
        self.location_label.setFont(font)
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        
        self.url_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.url_textEdit.setGeometry(QtCore.QRect(260, 250, 381, 41))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        
        self.url_textEdit.setFont(font)
        self.url_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.url_textEdit.setObjectName("url_textEdit")
        
        self.location_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.location_textEdit.setGeometry(QtCore.QRect(260, 370, 381, 41))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        
        self.location_textEdit.setFont(font)
        self.location_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.location_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.location_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.location_textEdit.setObjectName("location_textEdit")
        
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(670, 375, 111, 31))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")
        
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setGeometry(QtCore.QRect(340, 460, 151, 51))
        
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(140, 560, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.pause_resume_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_resume_button.setGeometry(QtCore.QRect(580, 560, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pause_resume_button.setFont(font)
        self.pause_resume_button.setObjectName("pause_resume_button")
        self.vid_name_label = QtWidgets.QLabel(self.centralwidget)
        self.vid_name_label.setGeometry(QtCore.QRect(110, 300, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(16)
        self.vid_name_label.setFont(font)
        self.vid_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vid_name_label.setObjectName("vid_name_label")
        self.vid_name_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.vid_name_textEdit.setGeometry(QtCore.QRect(260, 310, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        self.vid_name_textEdit.setFont(font)
        self.vid_name_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vid_name_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vid_name_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.vid_name_textEdit.setObjectName("vid_name_textEdit")
        self.yt_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.yt_progressBar.setGeometry(QtCore.QRect(330, 570, 211, 31))
        self.yt_progressBar.setProperty("value", 24)
        self.yt_progressBar.setObjectName("yt_progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Video Downloader"))
        self.app_title.setText(_translate("MainWindow", "Youtube Video Downloader"))
        self.url_label.setText(_translate("MainWindow", "Video URL"))
        self.location_label.setText(_translate("MainWindow", "Location"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.pause_resume_button.setText(_translate("MainWindow", "Pause"))
        self.vid_name_label.setText(_translate("MainWindow", "Video Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
