# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\YDD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
    
class Ui_MainWindow(object):
    """UI of the YVD Main Window."""
    
    def setupUi(self, MainWindow):
        """Build up this Window's UI."""
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.youtube_icon = QtWidgets.QLabel(self.centralwidget)
        self.youtube_icon.setGeometry(QtCore.QRect(340, 30, 141, 101))
        self.youtube_icon.setMaximumSize(QtCore.QSize(171, 16777215))
        self.youtube_icon.setText("")
        self.youtube_icon.setPixmap(QtGui.QPixmap("pics/youtube.png"))
        self.youtube_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.youtube_icon.setObjectName("youtube_icon")
        
        self.app_title = QtWidgets.QLabel(self.centralwidget)
        self.app_title.setGeometry(QtCore.QRect(190, 140, 471, 61))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(24)
        
        self.app_title.setFont(font)
        self.app_title.setAlignment(QtCore.Qt.AlignCenter)
        self.app_title.setObjectName("app_title")
        
        self.url_label = QtWidgets.QLabel(self.centralwidget)
        self.url_label.setGeometry(QtCore.QRect(100, 240, 131, 61))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(16)
        
        self.url_label.setFont(font)
        self.url_label.setAlignment(QtCore.Qt.AlignCenter)
        self.url_label.setObjectName("url_label")
        self.location_label = QtWidgets.QLabel(self.centralwidget)
        self.location_label.setGeometry(QtCore.QRect(100, 300, 121, 61))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(16)
        
        self.location_label.setFont(font)
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setObjectName("location_label")
        
        self.url_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.url_textEdit.setGeometry(QtCore.QRect(260, 250, 381, 41))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        
        self.url_textEdit.setFont(font)
        self.url_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.url_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.url_textEdit.setObjectName("url_textEdit")
        
        self.location_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.location_textEdit.setGeometry(QtCore.QRect(260, 310, 381, 41))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(16)
        
        self.location_textEdit.setFont(font)
        self.location_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.location_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.location_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.location_textEdit.setObjectName("location_textEdit")
        
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(670, 315, 111, 31))
        
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")

        # Bind the browse button to opening a folder dialog window
        self.browse_button.clicked.connect(lambda : self.browseButton_EventHandler(MainWindow))
        
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setGeometry(QtCore.QRect(340, 400, 151, 51))

        # Bind the download button to a checker and subsequently downloading video
        self.download_button.clicked.connect(lambda : self.downloadButton_EventHandler(MainWindow))
        
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(180, 490, 121, 51))

        # Bind the cancel button to its determined functionality
        self.cancel_button.clicked.connect(lambda : self.cancelButton_EventHandler(MainWindow))

        # Hide Cancel Button Inittialy
        self.cancel_button.hide()
        
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        
        self.pause_resume_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_resume_button.setGeometry(QtCore.QRect(520, 490, 121, 51))

        # Bind the pause/resume button to its respective functionality
        self.pause_resume_button.clicked.connect(lambda : self.pauseButton_EventHanlder(MainWindow))

        # Hide Resume Pause Button Initially
        self.pause_resume_button.hide()
        
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        
        self.pause_resume_button.setFont(font)
        self.pause_resume_button.setObjectName("pause_resume_button")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """Set the corresponding text to each PyQt5 GUI Widget."""
        
        MainWindow.setWindowTitle("Youtube Video Downloader")
        self.app_title.setText("Youtube Video Downloader")
        self.url_label.setText("Video URL")
        self.location_label.setText("Location")
        self.browse_button.setText("Browse")
        self.download_button.setText("Download")
        self.cancel_button.setText("Cancel")
        self.pause_resume_button.setText("Pause")

    def browseButton_EventHandler(self, MainWindow):
        """Execute action when the browse button is clicked."""

        MainWindow.browse_system(self.location_textEdit)

    def downloadButton_EventHandler(self, MainWindow):
        """Execute action when the download button is clicked."""

        MainWindow.download_operations({"URL"      : self.url_textEdit,
                                        "Location" : self.location_textEdit,
                                        "Cancel"   : self.cancel_button,
                                        "Pause"    : self.pause_resume_button})
        
    def cancelButton_EventHandler(self, MainWindow):
        """Execute action when the cancel button is clicked."""

        MainWindow.cancel_operations({"Download" : self.download_button,
                                      "Cancel"   : self.cancel_button,
                                      "Pause"    : self.pause_resume_button})

        


    def pauseButton_EventHanlder(self, MainWindow):
        """Execute action when the pause/resume button is clicked."""

        MainWindow.pause_or_resume({"Pause" : self.pause_resume_button})
        
